const gate=document.getElementById('gate'), site=document.getElementById('site'), envelope=document.getElementById('openInvite');
let audioCtx, gain, oscillator, soundOn=false;
function startSound(){if(audioCtx)return;audioCtx=new (window.AudioContext||window.webkitAudioContext)();gain=audioCtx.createGain();gain.gain.value=.018;gain.connect(audioCtx.destination);oscillator=audioCtx.createOscillator();oscillator.type='sine';oscillator.frequency.value=220;oscillator.connect(gain);oscillator.start();}
function toggleSound(){if(!audioCtx)startSound();soundOn=!soundOn;gain.gain.setTargetAtTime(soundOn?.018:0,audioCtx.currentTime,.15);document.getElementById('sound').textContent=soundOn?'♪':'·';}
document.getElementById('sound').addEventListener('click',toggleSound);
envelope.addEventListener('click',()=>{if(envelope.classList.contains('opening'))return;startSound();envelope.classList.add('opening');setTimeout(()=>{gate.classList.add('open');site.classList.add('live');site.setAttribute('aria-hidden','false');window.scrollTo({top:0,behavior:'instant'});},1050);});
const observer=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting)e.target.classList.add('in')}),{threshold:.12});document.querySelectorAll('.reveal').forEach(x=>observer.observe(x));
const target=new Date('2027-06-17T12:00:00+03:00');
function tick(){let d=Math.max(0,target-Date.now());let s=Math.floor(d/1000), days=Math.floor(s/86400);s%=86400;let h=Math.floor(s/3600);s%=3600;let m=Math.floor(s/60);s%=60;let vals={days,hours:h,minutes:m,seconds:s};for(const k in vals){const el=document.querySelector(`[data-unit="${k}"]`);if(el)el.textContent=String(k==='days'?days:vals[k]).padStart(2,'0')}}tick();setInterval(tick,1000);
const bar=document.querySelector('.progress span');addEventListener('scroll',()=>{const max=document.documentElement.scrollHeight-innerHeight;bar.style.width=(max?scrollY/max*100:0)+'%';});
const attendance=document.getElementById('attendance'), conditional=document.getElementById('conditional');document.querySelectorAll('.choice').forEach(btn=>btn.addEventListener('click',()=>{document.querySelectorAll('.choice').forEach(x=>x.classList.remove('active'));btn.classList.add('active');attendance.value=btn.dataset.value;conditional.classList.toggle('show',btn.dataset.value==='yes')}));
document.getElementById('rsvpForm').addEventListener('submit',e=>{e.preventDefault();if(!attendance.value){alert('Пожалуйста, выберите вариант ответа.');return}const data=Object.fromEntries(new FormData(e.target));data.createdAt=new Date().toISOString();const old=JSON.parse(localStorage.getItem('melaniaVadimRSVP')||'[]');old.push(data);localStorage.setItem('melaniaVadimRSVP',JSON.stringify(old));e.target.style.display='none';document.getElementById('success').classList.add('show');});
